name: "Context"
on:
  push:
    branches:
      - main
jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My steps"
        run: |
          echo "Acción actual: ${{ github.action }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Actor (quién hizo el push): ${{ github.actor }}"

